services:
  shopifyapp-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopifyapp-auth
    ports:
      - "${PORT:-9998}:9998"
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped
